pipeline{
  agent any
environment {
  PATH = "${PATH}:{gettfPath()}"
}
  stages{
    stage('tf init'){
      steps{
        sh "terraform init"
      }
    }
  }
}

def gettfPath(){
  def tfHome = tool name: 'terraform-12', type: 'terraform'
  return tfHome
}